"""
alert_manager.py

Creates and stores security alerts generated by the detection engine
"""


import json
from pathlib import Path
from datetime import datetime

ALERT_FILE = Path("alerts/alerts.json")


def load_alerts():
    """
    Load existing alerts
    """
    
    if not ALERT_FILE.exists():
        return []
    
    try:
        with open(ALERT_FILE, "r") as file:
            return json.load(file)
        
    except Exception:
        return []
    
    
def save_alerts(alerts):
    """
    Save alerts to disk.
    """
    
    ALERT_FILE.parent.mkdir(exist_ok=True)
    
    with open(ALERT_FILE, "w") as file:
        json.dump(alerts, file, indent=4)
        
        
def get_next_id(alerts):
    """
    Generate next alert ID
    """
    
    if not alerts:
        return 1
    
    return max(alert["id"] for alert in alerts) + 1


def create_alert(
    finding,
    severity,
    source_ip,
    user,
    mitre_technique,
    description
):
    """
    Create and save new alert.
    """
    
    alerts = load_alerts()
    
    alert = {
        "id": get_next_id(alerts),
        "timestamp": datetime.utcnow().isoformat(),
        "finding": finding,
        "severity": severity,
        "status": "OPEN",
        "source_ip": source_ip,
        "user": user,
        "mitre_technique": mitre_technique,
        "description": description  
    }
    
    alerts.append(alert)
    
    save_alerts(alerts)
    
    print(
        f"[ALERT]"
        f"{severity} | "
        f"{finding} | "
        f"{source_ip}"
    )
    
    return alert


def close_alert(alert_id):
    """
    Mark an alert as closed
    """
    
    alerts = load_alerts()
    
    for alert in alerts:
        if alert["id"] == alert_id:
            alert["status"] = "CLOSED"
            
    save_alerts(alerts)
    
    
def get_open_alerts():
    """
    Return all open alerts.
    """
    
    alerts = load_alerts()
    
    return [
        alert
        for alert in alerts
        if alert["status"] == "OPEN"
    ]
    
    
if __name__ == "__main__":
    
    create_alert(
        finding="Privilege Escalation",
        severity="HIGH",
        source_ip="192.168.1.100",
        user="developer",
        mitre_technique="T1098",
        description="AdministratorAccess policy attached."
    )